### ISSUE TITLE
Desenvolver Identidade VIsual

### ISSUE THREAD

**Issue by webertmaximiano** [Clube-Siga/agilizando-o-futuro#11]
Processos:

 >- Entendimento dos objetivos e valores do projeto
 >- Pesquisa de mercado e público-alvo
 >- Criação do nome
 >- Criação do slogan
 >- Desenvolvimento do logo
 >- Desenvolvimento da identidade visual
 >- Construção da presença online
 >- Aplicação do branding na versão final do site

O que já está definido:

>- Entendimento dos objetivos e valores do projeto ✅ 
>- Pesquisa de mercado e público-alvo ✅ 
>- Criação do nome ✅
>- Criação do slogan  ✅
>- Desenvolvimento do logo ✅ 
>-  Desenvolvimento da identidade visual ✅ 
>- Construção da presença online ✅
>- Aplicação da IDV no protótipo ✅

[Clique aqui](https://www.figma.com/file/pPf4miedhxerbil7jeZQof/Agilizando-o-Futuro?type=design&mode=design&t=yPTtiYE3zJUfrQbq-1) para ver a apresentação no Figma

[Clique aqui](https://docs.google.com/document/d/1viO2mjg2wPnKs4LrjShjwfwvSWnntNLRBGOPGz28rhs/edit?usp=sharing) para acessar os arquivos (Tipografia, paleta de cores)

[Clique aqui](https://drive.google.com/drive/folders/1doHdP7NLcL1lHlhru_ZxavDZvFw2GOQw?usp=sharing) para acessar as imagens do site

**Comment by witorlinhares** [comment]
Processos:

>Entendimento dos objetivos e valores do projeto
   Pesquisa de mercado e público-alvo
   Criação do nome e slogan
   Desenvolvimento do logo
   Desenvolvimento da identidade visual
   Criação de materiais de comunicação
   Construção da presença online

O que já está definido:

>Entendimento dos objetivos e valores do projeto ❌ 
   Pesquisa de mercado e público-alvo ❌ 
   Criação do nome e slogan ✅ 
   Desenvolvimento do logo ❌ 
   Desenvolvimento da identidade visual ❌ 
   Criação de materiais de comunicação ❌ 
   Construção da presença online ❌
