### ISSUE TITLE
Correção do envio do formulário (em produção)

### ISSUE THREAD

**Issue by naejshaw** [Clube-Siga/agilizando-o-futuro#40]

**Comment by webertmaximiano** [comment]
Correções realizadas @naejshaw @alexandro077 @witorlinhares Testem, alterações no meu branch e comentarios, depois podemos fazer uma revisão juntos apos a dailly

**Comment by naejshaw** [comment]
Olhei as alterações realizadas, juntamente com os comentários e acredito ter compreendido bem, tanto os problemas quanto as soluções implementadas.

**Comment by naejshaw** [comment]
Conforme dito no discord, foi realizado o teste após as correções e foi observado o bom funcionamento do envio do formulário. Com isso, irei fechar o issue após a resolução do mesmo.
