### ISSUE TITLE
Criar o wireframe da página

### ISSUE THREAD

**Issue by webertmaximiano** [Clube-Siga/agilizando-o-futuro#5]

**Comment by witorlinhares** [comment]
[Clique aqui](https://www.figma.com/file/2r74tFZhkTL8hWcp1KlVOu/wireframe-streamlining?type=design&node-id=0%3A1&mode=design&t=5T2d1Qazii9VXiry-1) para visualizar no Figma.




![Image](https://github.com/Clube-Siga/agilizando-o-fututo/assets/154279407/2cd2a234-dadc-4384-865e-4fb205c647a4)

**Comment by webertmaximiano** [comment]
ok
